### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by Superfly1337** [TheMysteriousVincent/LiveInLife#1]
is there a guide how to use this ?
how to set it up

**Comment by pixlcrashr** [comment]
Actually... I didnt had the time yet to write a description for this mod. And I either do not know if the uploaded stuff here on github is working well w/out erros.
Nevertheless i will do a description in the next few days.

**Comment by Superfly1337** [comment]
Possible that you want to start up a server with us? (We have the servers) or help us setup one ?

Sendt fra min iPhone

**Comment by pixlcrashr** [comment]
@Superfly1337 Im already developing on another server. But this project is open source and is also used in our project. By the time i will update this mod again.

**Comment by pixlcrashr** [comment]
[Added wiki entry](https://github.com/AGPHeaddikilla/LiveInLife/wiki/Installation)
