### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by psycodeliccircus** [TheMysteriousVincent/LiveInLife#2]
Do not have a database?
No mission folder?

@AGPHeaddikilla

**Comment by pixlcrashr** [comment]
Sorry for that @psycodeliccircus. There are no frequently updates because this "mod" is still in development status.
As you wish I can add an example folder for usage but this would be time consuming.

**Comment by psycodeliccircus** [comment]
Could release to community agent helps you friend.
Logic be can.
@AGPHeaddikilla

**Comment by pixlcrashr** [comment]
@psycodeliccircus true story... In the next few days I will merge all of that stuff to GitHub again.

**Comment by psycodeliccircus** [comment]
@AGPHeaddikilla Thanks friend I want to test your mods and see what I can help you with.

**Comment by pixlcrashr** [comment]
@psycodeliccircus Also there is no common known "Altis_Life.Altis" mission folder. Everything is running with client pre/post init functions.
So a maybe used mission folder "just" contains configuration files for LiveInLife and nothing else.

**Comment by psycodeliccircus** [comment]
@AGPHeaddikilla But how would the database be created?

**Comment by pixlcrashr** [comment]
Yep... I didn't created a .sql file for the default database yet.

**Comment by psycodeliccircus** [comment]
@AGPHeaddikilla Would you like to create an agent to make a server to see what the staff thinks about the mod?

**Comment by pixlcrashr** [comment]
What do you mean by "agent"?

**Comment by psycodeliccircus** [comment]
@AGPHeaddikilla I bought a dedicated one on ovh so to put the mod la to wheel for agent to see how it goes online.

**Comment by pixlcrashr** [comment]
Isnt this covered by the [installation manual](https://github.com/AGPHeaddikilla/LiveInLife/wiki/Installation)? By the way i will create the database file soon.

**Comment by psycodeliccircus** [comment]
@AGPHeaddikilla Do not need to configure anything on the mission?

**Comment by psycodeliccircus** [comment]
```
class CfgFunctions {
    class lilc {
        class recompile { file = "recompile.sqf"; };
    };

    class lilc_actions {
        file = "@LiveInLifeClient\lilc_actions\functions";
        class hideCorpse {};
    };
};
```

**Comment by psycodeliccircus** [comment]
#recompile.sqf
`lilc_actions_fnc_init = compile preprocessFileLineNumbers "@LiveInLifeClient\lilc_actions\functions\fn_init.sqf";`

**Comment by pixlcrashr** [comment]
The problem is that you cannot (re-)compile functions of mods while on a server (the server can not allow that).
Maybe I will switch to CBA functions although I do not like the way functions are declared.

**Comment by pixlcrashr** [comment]
I have to mention that the path of client mods are the following format `x\lilc\addons\<mod>` - pretty similar to the server's one `x\lils\addons\<mod>`.

**Comment by pixlcrashr** [comment]
@psycodeliccircus Just wait until I updated the mission (should happen at weekend).

**Comment by pixlcrashr** [comment]
Updated 48d93e93b28f9ac5e9826a797580fe14064e82f8
