### ISSUE TITLE
Paycheck does not save

### ISSUE THREAD

**Issue by pixlcrashr** [TheMysteriousVincent/LiveInLife#22]
![lilc_paycheck_active](https://steamuserimages-a.akamaihd.net/ugc/903401556512411268/D24E3A6BAA23EA5D5DFB2C9DEC446B0A97C65291/)

**Comment by pixlcrashr** [comment]
fixed with 578125cab5c2a55b9c72f07eacb99c6b87a7e14e

**Comment by pixlcrashr** [comment]
Paycheck does not get send anywhere.

**Comment by pixlcrashr** [comment]
fixed with 8d238285200e20f1da18d40ca6b9f01986bc69b2

**Comment by TheMysteriousVincent** [comment]
fixed with 6063dba51cc5a096653b19c3bda0f6b887c87ac2

**Comment by pixlcrashr** [comment]
fixed with 79930fa2db84a9433c51559efea5ca526b053ab6
