### ISSUE TITLE
deploys the system on the metropolis map?

### ISSUE THREAD

**Issue by psycodeliccircus** [TheMysteriousVincent/LiveInLife#29]
Can I use it on the Metropolis map?
@TheMysteriousVincent

**Comment by pixlcrashr** [comment]
@psycodeliccircus Well, sure you can deploy this mod on any map. You just have to configure your mission on your own.
The documentation of configs and their properties does not exists yet.

**Comment by pixlcrashr** [comment]
#deprecated
