### ISSUE TITLE
Mission in altis?

### ISSUE THREAD

**Issue by psycodeliccircus** [TheMysteriousVincent/LiveInLife#3]
Could you make an altis version?

@AGPHeaddikilla

**Comment by pixlcrashr** [comment]
@psycodeliccircus Just move your own mission file in the mission folder given in the lil0.8 branch. Then you only have to rename the "Tanoa" to "Altis".
Or you just copy the files in "LiveInLife.Tanoa" to your Altis mission folder.

**Comment by psycodeliccircus** [comment]
Plus it does not have bank location NPCs etc?
@AGPHeaddikilla

**Comment by pixlcrashr** [comment]
Thats correct. I say it again: Currently there is no big documentation about all `addActions` yet.
