### ISSUE TITLE
Mission 

### ISSUE THREAD

**Issue by Superfly1337** [TheMysteriousVincent/LiveInLife#30]
You have an exemple mission file I can’t try this with?

**Comment by pixlcrashr** [comment]
What do you mean by that? Do you run this on a server, host or in the editor?
Please give me a detailed description on that-

**Comment by Superfly1337** [comment]
Where can I change the db settings?

**Comment by Superfly1337** [comment]
12:11:19 [8832,45.41,0,"CBA_VERSIONING: cba=3.5.0.171204, ace=3.12.1.31, "]
12:11:19 "[LiveInLifeServer][extDB3][674:17:34][NORMAL]: extDB3: Version: 1.031"
12:11:20 Warning: 1008 ms spent in callExtension calling name: "extDB3", function: "9:ADD_DATABASE:LiveInLife"
12:11:20 "[LiveInLifeServer][extDB3][674:17:35][ERROR]: extDB3: Failed to connect to database LiveInLife!"

**Comment by pixlcrashr** [comment]
That makes sense to me. I didn't create an example extDB3 config file in the @LiveInLifeServer folder. This should be fixed with 03ec841a41dd8bf02877b03398e1a66247b6657b.
To get things work, you just have to copy the recently added `extdb-conf.ini` file to your @LiveInLifeServer folder. Then you have to customize all database credentials.

I'm sorry for that incident.

**Comment by Superfly1337** [comment]
And I get this ? mpmissions\LiveInLife.Tanoa\config\CfgVehicleShops.cpp, line 11: /CfgVehicleShops/vehicles_shop_1/vehicles/: '<' encountered instead of '{'
12:47:22 Warning Message: Config : some input after EndOfFile.

And is it supposed to be marked shops on the map?

**Comment by pixlcrashr** [comment]
I just fixed that particular config with 271b42c5b0c3e5ed9363e4c1e370845651e03f99.<br>
But actually, the LiveInLife.Tanoa mission is just an *example*. Although, I know that there is nearly no documentation for that configs.
I try to add this config docs in the next few days.

**Comment by Superfly1337** [comment]
Okei Thanks, i Cant see any markings on the map for stores or anythin But the mod looks good

**Comment by pixlcrashr** [comment]
Thanks! I appreciate your feedback.

**Comment by pixlcrashr** [comment]
If I have created the documentation for this mod, you can customize your mission by yourself.

Thus, I will close this issue for now.
