### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by Superfly1337** [TheMysteriousVincent/LiveInLife#31]
[NORMAL]: extDB3: uisleep [4]: 51.932"
 6:05:13 Suspending not allowed in this context
 6:05:13 Error in expression <, "extDB3"] call lilc_log_fnc_diag_log;
uiSleep 0.1;
}
else
{
_isLooping = false>
 6:05:13   Error position: <uiSleep 0.1;
}
else
{
_isLooping = false>
 6:05:13   Error Generic error in expression
 6:05:13 File \x\lils\addons\database\functions\fn_async.sqf [lils_database_fnc_async], line 50

**Comment by Superfly1337** [comment]
Going to try waitUntil {uiSleep 0.2;}; instead

**Comment by pixlcrashr** [comment]
@Superfly1337 `waitUntil { uiSleep 0.2; }` can not work because of two reasons:
1. There is no boolean condition returned by `uiSleep` and
2. This loop will be infinite.

This error maybe occurs because the script is called in an unscheduled environment.

**Comment by Superfly1337** [comment]
Aha I get a black screen when I join, and nothing happens

**Comment by Superfly1337** [comment]
Can this be the reason?

**Comment by pixlcrashr** [comment]
Hard to tell. Maybe you add some full client and server logs.

**Comment by CptSigurd** [comment]
RPT

**Comment by CptSigurd** [comment]
RPT

[Arma3_x64_2018-01-28_11-02-17.txt](https://github.com/TheMysteriousVincent/LiveInLife/files/1670980/Arma3_x64_2018-01-28_11-02-17.txt)
[arma3server_x64_2018-01-28_06-04-21.txt](https://github.com/TheMysteriousVincent/LiveInLife/files/1670981/arma3server_x64_2018-01-28_06-04-21.txt)

**Comment by Superfly1337** [comment]
You have the rpt files there, and here database_defaultProtocolName in cfgservermaster what do I insert there or leave empty?

**Comment by pixlcrashr** [comment]
@Superfly1337 You can leave it empty.

**Comment by pixlcrashr** [comment]
@Superfly1337 Is there an entry in your database table `ACCOUNT_DATA`?

**Comment by Superfly1337** [comment]
Yes and we could choose name and suff but after the someVhircleid then it’s black

**Comment by pixlcrashr** [comment]
May you can upload a screenshot?

**Comment by Superfly1337** [comment]
Just a black background when press esc get the log off and all. And when push I get up inventory and can hear walking

**Comment by Superfly1337** [comment]
Server ip
![f7f35855-7826-4e6f-97d6-6da784a4a4a8](https://user-images.githubusercontent.com/29904425/35481777-112615ea-045d-11e8-8512-db5ac98c1aa4.jpeg)

**Comment by TheMysteriousVincent** [comment]
@Superfly1337 Did you created a mission on your own?

**Comment by Superfly1337** [comment]
Yes placed out 4 civs on Tanoa

**Comment by Superfly1337** [comment]
Yes I added 4 civs on tanoa

**Comment by pixlcrashr** [comment]
May you restart the server?

**Comment by Superfly1337** [comment]
Did it now sendt you server info on email too

Hilsen Jørn

**Comment by pixlcrashr** [comment]
fixed things with ec27af711b9922a5b409af750ef832db02742c35.

The server should now work fine.
