### ISSUE TITLE
black screen after spawn

### ISSUE THREAD

**Issue by ZeroLifeTime** [TheMysteriousVincent/LiveInLife#42]
Hello,

after the spawn screen i get an blackscreen but i can hear the running steps...

RPT: https://pastebin.com/bP5RBvAG
EXTDB3: https://pastebin.com/1CL01DPJ

**Comment by pixlcrashr** [comment]
`Scripting function 'lils_login_fnc_getprofiles' is not allowed to be remotely executed` in line 847.

You probably did load the Altis Life missionfile:
```
19:01:16 "----------------------------------------------------------------------------------------------------"
19:01:16 "---------------------------------- Starting Altis Life Server Init ---------------------------------"
19:01:16 "------------------------------------------ Version 5.0.0 -------------------------------------------"
19:01:16 "----------------------------------------------------------------------------------------------------"
19:01:16 Attempt to override final function - bis_fnc_storeparamsvalues_data
19:01:16 "----------------------------------------------------------------------------------------------------"
19:01:16 "               End of Altis Life Server Init :: Total Execution Time 0.160999 seconds "
19:01:16 "----------------------------------------------------------------------------------------------------"
```

Do NOT do that. Please create your own mission file or use the template saved in `LiveInLife.Tanoa/`.

**Comment by ZeroLifeTime** [comment]
i cant find a template there

**Comment by pixlcrashr** [comment]
I see... Well, I did not create any installation documentation yet.
Thus, you just have to create a mission with a custom spawn position and place some playable civilian units on the map you choose.
And, of course copy given configuration files including description.ext from `LiveInLife.Tanoa/` into your mission folder.

**Comment by ZeroLifeTime** [comment]
i saw you come from Germany can we talk in Ts ?

**Comment by ZeroLifeTime** [comment]
bc im from Germany too ;)

**Comment by pixlcrashr** [comment]
I do not like solving problems with Teamspeak for an Open Source project because if problems were not documented for others, the same issues will be opened and opened again.

You can see that helping people outside the GitHub-"box" creates much more unnecessary maintenance work for me.

Besides that, I clearly **do not have the time** to help every single person via Teamspeak, etc.

**Comment by ZeroLifeTime** [comment]
i dont know how the mision have to look like...

**Comment by pixlcrashr** [comment]
What do you mean by that? The mission itself regarding placing units, e.g. or do you mean what files do you need to create a mission?

**Comment by ZeroLifeTime** [comment]
which files i need and hw i can use your tools.

**Comment by pixlcrashr** [comment]
@ZeroLifeTime First, you have to load the `@LiveInLifeClient` mod whether from Steam or downloaded from source.

Next, you have to create a mission folder called whatever you like. How to create a mission should be a basic prerequisite.

After that, you copy the config files from the GitHub mission `LiveInLife.Tanoa` to your mission folder containing a `mission.sqm` file already.

The `mission.sqm` should already contain some playable units and a respawn point placed with an empty marker and second, a respawn point which you should have placed with a liveinlife dynamic position module.

Now you just have to pack and upload your mission folder to your server and you are ready to go.

You can see further information for the installation of clients and servers [here](https://github.com/TheMysteriousVincent/LiveInLife/wiki/Installation).

**Comment by pixlcrashr** [comment]
Is there anything left to help you with?
